services:
  selenium:
    image: selenium/standalone-chrome:97.0-20250202
    container_name: selenium
    restart: unless-stopped
    shm_size: 1g
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - majula

  app:
    build: .
    container_name: lmdstate
    restart: unless-stopped
    depends_on:
      - selenium
    env_file:
      - .env
    environment:
      - SELENIUM_REMOTE_URL=${SELENIUM_REMOTE_URL}
      - N8N_URL=${N8N_URL}
      - PAGE=${PAGE}
    ports:
      - "8100:8000"
    networks:
      - majula

networks:
  majula:
    external: true
